  server:
    port: 8080

  spring:
    datasource:
      dynamic:
        primary: master
        strict: false
        datasource:
          master:
            url: jdbc:mysql://localhost:3306/chat_all
            username: root
            password: pNn6ZWBTT1zHtF3JLfK5
            driver-class-name: com.mysql.cj.jdbc.Driver
